apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sandboxes.yh-ha.duckdns.org
spec:
  group: yh-ha.duckdns.org
  scope: Namespaced
  names:
    plural: sandboxes
    singular: sandbox
    kind: SandBox
    shortNames:
    - sb
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
