FROM golang:1.16-alpine3.14 as builder
ENV CGO_ENABLED 0

ADD . /src
WORKDIR /src
RUN go get
RUN GOTRACEBACK=all go build -gcflags "all=-N -l" -o metacontroller
RUN go get github.com/go-delve/delve/cmd/dlv
# -------------------------

FROM alpine:3.14
COPY --from=builder /src/metacontroller /metacontroller
COPY --from=builder /go/bin/dlv /

EXPOSE 8000 40000

ENTRYPOINT ["./dlv","--listen=:40000","--headless=true","--api-version=2","--accept-multiclient","exec","./metacontroller"]
